version: 2
updates:
  # Configuration pour les dépendances Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "project-maintainer"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "pip"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Configuration pour les dépendances Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "project-maintainer"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Configuration pour les dépendances GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "project-maintainer"
    reviewers:
      - "project-maintainer"
    commit-message:
      prefix: "github-actions"
      include: "scope"