"""Add id column to post_tag table

Revision ID: 9afa5752d581
Revises: eb1a0417c443
Create Date: 2025-03-02 07:16:12.174532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afa5752d581'
down_revision: Union[str, None] = 'eb1a0417c443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_tags_id', table_name='post_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_tags_id', 'post_tags', ['id'], unique=False)
    # ### end Alembic commands ###
